name: CI

jobs:
  build:
    runs-on: ${{ matrix.os }}
    on:
      push:
        branches: [master]
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: npm install
      - run: npm run release

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

  verify:
    runs-on: ${{ matrix.os }}
    on:
      pull_requests:
        branches: [master]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: npm install
      - run: npm run compile

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
